- name: Deploy Node.js App with NGINX
  hosts: webserver
  become: yes

  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Node.js
      shell: |
        curl -sL https://rpm.nodesource.com/setup_18.x | bash -
        yum install -y nodejs
      args:
        executable: /bin/bash

    - name: Copy Node.js app
      copy:
        src: ./app/
        dest: /var/www/app/

    - name: Install dependencies
      shell: |
        cd /var/www/app
        npm install
      args:
        chdir: /var/www/app

    - name: Start app
      shell: |
        nohup node app.js > /var/log/nodeapp.log 2>&1 &
      args:
        chdir: /var/www/app

    - name: Deploy nginx reverse proxy config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/nodeapp.conf
        mode: '0644'

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
