- name: Deploy Node.js App with NGINX and RDS
  hosts: webserver
  become: yes

  vars:
    db_host: "{{ lookup('env', 'DB_HOST') }}"
    db_port: "{{ lookup('env', 'DB_PORT') }}"
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"

  tasks:
    - name: Install NGINX
      yum:
        name: nginx
        state: present

    - name: Start and enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Node.js
      shell: |
        curl -sL https://rpm.nodesource.com/setup_18.x | bash -
        yum install -y nodejs
      args:
        executable: /bin/bash

    - name: Copy Node.js app
      copy:
        src: ./app/
        dest: /var/www/app/

    - name: Generate .env file from template
      template:
        src: .env.j2
        dest: /var/www/app/.env
        mode: '0644'

    - name: Install dependencies
      shell: npm install
      args:
        chdir: /var/www/app

    - name: Start Node.js app
      shell: nohup node app.js > /var/log/nodeapp.log 2>&1 &
      args:
        chdir: /var/www/app

    - name: Deploy NGINX reverse proxy config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/nodeapp.conf
        mode: '0644'

    - name: Reload NGINX
      service:
        name: nginx
        state: reloaded
